spring:
  datasource:
    url: jdbc:mysql://localhost/school
    username: root
    password: Flavio10.

  jpa:
    open-in-view: "false"
    hibernate:
      use-new-id-generator-mappings: "false"
      ddl-auto: update
    show-sql: "false"
